name = "backend"
compatibility_date = "2024-08-12"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYzYyNmRjZDAtZTc2YS00OWQ0LWJiZmMtODA4Y2E0ZWMyNjdhIiwidGVuYW50X2lkIjoiZjhjNjQxYzJmNWY2ZWRjYWUzZjRmNjVjZDE0Mjk4ZmJjN2ZhMGI1YzhjYjI0MjkyNzNmNTQ3ZGMyNTdmMjUxZiIsImludGVybmFsX3NlY3JldCI6IjkwMWRlZmEzLTBjYjktNDQwNS1iZDU5LWEyMDgyMjU0YjM1NSJ9.zeZ9BXBRU2kt0PhZa5mMlvVIZojFe6ExOGaAZZaUowY"


JWT_SECRET="Subham@123"